name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t triplix/relaxinemaclient:latest -f Dockerfile
      - name: publish
        run: |
          docker login -u triplix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push triplix/relaxinemaclient:latest
